config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'

  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    require 'HTTParty'
    require 'json'


    response = HTTParty.get("https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest", 
            headers: {
                Accept: 'application/json',
                'X-CMC_PRO_API_KEY': '098c2c7c-a993-4fb8-86ac-e56ed0cc1c81',
                symbol: 'BTC'
            },
            parameters: {
                start: '1',
                limit: '2',
                convert: 'AUD',
            }
        )
      @content = JSON.parse(response.body)
      @contentData = @content['data']
      #@contentDataHash = JSON.parse(@contentData)

  end




  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" <%= link_to "Crypto Tracker", root_path %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" <%= link_to "Home", root_path %> </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" <%= link_to "About Us", home_about_path %> </a>
        </li>
      </ul>
    </div>
  </div>
</nav>



    
    

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Home</h1>

<br/>


<%= for x in @contentData[0] do %>
<%= puts x %>
<%= end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>